# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        exclude: ^src/utils/helper_functions.tsx

  - repo: https://github.com/hackaugusto/pre-commit-cargo
    rev: v1.0.0
    hooks:
      # Allows cargo fmt to modify the source code prior to the commit
      - id: cargo
        name: Cargo fmt
        args: ['+stable', 'fmt', '--all']
        stages: [commit]
        files: ^examples/playground/miden-wasm/.*\.rs$
      # Requires code to be properly formatted prior to pushing upstream
      - id: cargo
        name: Cargo fmt --check
        args: ['+stable', 'fmt', '--all', '--check']
        stages: [push, manual]
        files: ^examples/playground/miden-wasm/.*\.rs$
      - id: cargo
        name: Cargo check --all-targets
        args: ['+stable', 'check', '--all-targets']
        files: ^examples/playground/miden-wasm/.*\.rs$
      - id: cargo
        name: Cargo check --all-targets --no-default-features
        args: ['+stable', 'check', '--all-targets', '--no-default-features']
        files: ^examples/playground/miden-wasm/.*\.rs$
      - id: cargo
        name: Cargo check --all-targets --all-features
        args: ['+stable', 'check', '--all-targets', '--all-features']
        files: ^examples/playground/miden-wasm/.*\.rs$
      # Unlike fmt, clippy will not be automatically applied
      - id: cargo
        name: Cargo clippy
        args:
          [
            '+nightly',
            'clippy',
            '--workspace',
            '--',
            '--deny',
            'clippy::all',
            '--deny',
            'warnings'
          ]
        files: ^examples/playground/miden-wasm/.*\.rs$
